// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: usd_sync.proto
// Protobuf C++ Version: 5.29.3

#include "usd_sync.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
              template <typename>
PROTOBUF_CONSTEXPR WatchRequest::WatchRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct WatchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WatchRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WatchRequestDefaultTypeInternal() {}
  union {
    WatchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WatchRequestDefaultTypeInternal _WatchRequest_default_instance_;

inline constexpr USDUpdateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR USDUpdateResponse::USDUpdateResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct USDUpdateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR USDUpdateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~USDUpdateResponseDefaultTypeInternal() {}
  union {
    USDUpdateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 USDUpdateResponseDefaultTypeInternal _USDUpdateResponse_default_instance_;

inline constexpr USDUpdateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : usd_file_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR USDUpdateRequest::USDUpdateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct USDUpdateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR USDUpdateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~USDUpdateRequestDefaultTypeInternal() {}
  union {
    USDUpdateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 USDUpdateRequestDefaultTypeInternal _USDUpdateRequest_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_usd_5fsync_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_usd_5fsync_2eproto = nullptr;
const ::uint32_t
    TableStruct_usd_5fsync_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::USDUpdateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::USDUpdateRequest, _impl_.usd_file_path_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::USDUpdateResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::USDUpdateResponse, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::WatchRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::USDUpdateRequest)},
        {9, -1, -1, sizeof(::USDUpdateResponse)},
        {18, -1, -1, sizeof(::WatchRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_USDUpdateRequest_default_instance_._instance,
    &::_USDUpdateResponse_default_instance_._instance,
    &::_WatchRequest_default_instance_._instance,
};
const char descriptor_table_protodef_usd_5fsync_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016usd_sync.proto\")\n\020USDUpdateRequest\022\025\n\r"
    "usd_file_path\030\001 \001(\t\"$\n\021USDUpdateResponse"
    "\022\017\n\007message\030\001 \001(\t\"\016\n\014WatchRequest2y\n\007USD"
    "Sync\0226\n\rSendUSDUpdate\022\021.USDUpdateRequest"
    "\032\022.USDUpdateResponse\0226\n\017WatchUSDUpdates\022"
    "\r.WatchRequest\032\022.USDUpdateResponse0\001b\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_usd_5fsync_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_usd_5fsync_2eproto = {
    false,
    false,
    244,
    descriptor_table_protodef_usd_5fsync_2eproto,
    "usd_sync.proto",
    &descriptor_table_usd_5fsync_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_usd_5fsync_2eproto::offsets,
    file_level_enum_descriptors_usd_5fsync_2eproto,
    file_level_service_descriptors_usd_5fsync_2eproto,
};
// ===================================================================

class USDUpdateRequest::_Internal {
 public:
};

USDUpdateRequest::USDUpdateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:USDUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE USDUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::USDUpdateRequest& from_msg)
      : usd_file_path_(arena, from.usd_file_path_),
        _cached_size_{0} {}

USDUpdateRequest::USDUpdateRequest(
    ::google::protobuf::Arena* arena,
    const USDUpdateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  USDUpdateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:USDUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE USDUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : usd_file_path_(arena),
        _cached_size_{0} {}

inline void USDUpdateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
USDUpdateRequest::~USDUpdateRequest() {
  // @@protoc_insertion_point(destructor:USDUpdateRequest)
  SharedDtor(*this);
}
inline void USDUpdateRequest::SharedDtor(MessageLite& self) {
  USDUpdateRequest& this_ = static_cast<USDUpdateRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.usd_file_path_.Destroy();
  this_._impl_.~Impl_();
}

inline void* USDUpdateRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) USDUpdateRequest(arena);
}
constexpr auto USDUpdateRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(USDUpdateRequest),
                                            alignof(USDUpdateRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull USDUpdateRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_USDUpdateRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &USDUpdateRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<USDUpdateRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &USDUpdateRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<USDUpdateRequest>(), &USDUpdateRequest::ByteSizeLong,
            &USDUpdateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(USDUpdateRequest, _impl_._cached_size_),
        false,
    },
    &USDUpdateRequest::kDescriptorMethods,
    &descriptor_table_usd_5fsync_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* USDUpdateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> USDUpdateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::USDUpdateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string usd_file_path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(USDUpdateRequest, _impl_.usd_file_path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string usd_file_path = 1;
    {PROTOBUF_FIELD_OFFSET(USDUpdateRequest, _impl_.usd_file_path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\15\0\0\0\0\0\0"
    "USDUpdateRequest"
    "usd_file_path"
  }},
};

PROTOBUF_NOINLINE void USDUpdateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:USDUpdateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.usd_file_path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* USDUpdateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const USDUpdateRequest& this_ = static_cast<const USDUpdateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* USDUpdateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const USDUpdateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:USDUpdateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string usd_file_path = 1;
          if (!this_._internal_usd_file_path().empty()) {
            const std::string& _s = this_._internal_usd_file_path();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "USDUpdateRequest.usd_file_path");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:USDUpdateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t USDUpdateRequest::ByteSizeLong(const MessageLite& base) {
          const USDUpdateRequest& this_ = static_cast<const USDUpdateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t USDUpdateRequest::ByteSizeLong() const {
          const USDUpdateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:USDUpdateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string usd_file_path = 1;
            if (!this_._internal_usd_file_path().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_usd_file_path());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void USDUpdateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<USDUpdateRequest*>(&to_msg);
  auto& from = static_cast<const USDUpdateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:USDUpdateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_usd_file_path().empty()) {
    _this->_internal_set_usd_file_path(from._internal_usd_file_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void USDUpdateRequest::CopyFrom(const USDUpdateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:USDUpdateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void USDUpdateRequest::InternalSwap(USDUpdateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.usd_file_path_, &other->_impl_.usd_file_path_, arena);
}

::google::protobuf::Metadata USDUpdateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class USDUpdateResponse::_Internal {
 public:
};

USDUpdateResponse::USDUpdateResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:USDUpdateResponse)
}
inline PROTOBUF_NDEBUG_INLINE USDUpdateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::USDUpdateResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

USDUpdateResponse::USDUpdateResponse(
    ::google::protobuf::Arena* arena,
    const USDUpdateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  USDUpdateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:USDUpdateResponse)
}
inline PROTOBUF_NDEBUG_INLINE USDUpdateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void USDUpdateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
USDUpdateResponse::~USDUpdateResponse() {
  // @@protoc_insertion_point(destructor:USDUpdateResponse)
  SharedDtor(*this);
}
inline void USDUpdateResponse::SharedDtor(MessageLite& self) {
  USDUpdateResponse& this_ = static_cast<USDUpdateResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* USDUpdateResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) USDUpdateResponse(arena);
}
constexpr auto USDUpdateResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(USDUpdateResponse),
                                            alignof(USDUpdateResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull USDUpdateResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_USDUpdateResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &USDUpdateResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<USDUpdateResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &USDUpdateResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<USDUpdateResponse>(), &USDUpdateResponse::ByteSizeLong,
            &USDUpdateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(USDUpdateResponse, _impl_._cached_size_),
        false,
    },
    &USDUpdateResponse::kDescriptorMethods,
    &descriptor_table_usd_5fsync_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* USDUpdateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> USDUpdateResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::USDUpdateResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(USDUpdateResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(USDUpdateResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\7\0\0\0\0\0\0"
    "USDUpdateResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void USDUpdateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:USDUpdateResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* USDUpdateResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const USDUpdateResponse& this_ = static_cast<const USDUpdateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* USDUpdateResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const USDUpdateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:USDUpdateResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "USDUpdateResponse.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:USDUpdateResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t USDUpdateResponse::ByteSizeLong(const MessageLite& base) {
          const USDUpdateResponse& this_ = static_cast<const USDUpdateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t USDUpdateResponse::ByteSizeLong() const {
          const USDUpdateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:USDUpdateResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void USDUpdateResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<USDUpdateResponse*>(&to_msg);
  auto& from = static_cast<const USDUpdateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:USDUpdateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void USDUpdateResponse::CopyFrom(const USDUpdateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:USDUpdateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void USDUpdateResponse::InternalSwap(USDUpdateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata USDUpdateResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WatchRequest::_Internal {
 public:
};

WatchRequest::WatchRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:WatchRequest)
}
WatchRequest::WatchRequest(
    ::google::protobuf::Arena* arena,
    const WatchRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WatchRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:WatchRequest)
}

inline void* WatchRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WatchRequest(arena);
}
constexpr auto WatchRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WatchRequest),
                                            alignof(WatchRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WatchRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WatchRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WatchRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<WatchRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WatchRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<WatchRequest>(), &WatchRequest::ByteSizeLong,
            &WatchRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WatchRequest, _impl_._cached_size_),
        false,
    },
    &WatchRequest::kDescriptorMethods,
    &descriptor_table_usd_5fsync_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WatchRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> WatchRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::WatchRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata WatchRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_usd_5fsync_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
