# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usd_sync.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'usd_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusd_sync.proto\")\n\x10USDUpdateRequest\x12\x15\n\rusd_file_path\x18\x01 \x01(\t\"$\n\x11USDUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0cWatchRequest2y\n\x07USDSync\x12\x36\n\rSendUSDUpdate\x12\x11.USDUpdateRequest\x1a\x12.USDUpdateResponse\x12\x36\n\x0fWatchUSDUpdates\x12\r.WatchRequest\x1a\x12.USDUpdateResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usd_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USDUPDATEREQUEST']._serialized_start=18
  _globals['_USDUPDATEREQUEST']._serialized_end=59
  _globals['_USDUPDATERESPONSE']._serialized_start=61
  _globals['_USDUPDATERESPONSE']._serialized_end=97
  _globals['_WATCHREQUEST']._serialized_start=99
  _globals['_WATCHREQUEST']._serialized_end=113
  _globals['_USDSYNC']._serialized_start=115
  _globals['_USDSYNC']._serialized_end=236
# @@protoc_insertion_point(module_scope)
