# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usd_sync_pb2 as usd__sync__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usd_sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class USDSyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUSDUpdate = channel.unary_unary(
                '/USDSync/SendUSDUpdate',
                request_serializer=usd__sync__pb2.USDUpdateRequest.SerializeToString,
                response_deserializer=usd__sync__pb2.USDUpdateResponse.FromString,
                _registered_method=True)
        self.WatchUSDUpdates = channel.unary_stream(
                '/USDSync/WatchUSDUpdates',
                request_serializer=usd__sync__pb2.WatchRequest.SerializeToString,
                response_deserializer=usd__sync__pb2.USDUpdateResponse.FromString,
                _registered_method=True)


class USDSyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendUSDUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchUSDUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_USDSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendUSDUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUSDUpdate,
                    request_deserializer=usd__sync__pb2.USDUpdateRequest.FromString,
                    response_serializer=usd__sync__pb2.USDUpdateResponse.SerializeToString,
            ),
            'WatchUSDUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchUSDUpdates,
                    request_deserializer=usd__sync__pb2.WatchRequest.FromString,
                    response_serializer=usd__sync__pb2.USDUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'USDSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('USDSync', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class USDSync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendUSDUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/USDSync/SendUSDUpdate',
            usd__sync__pb2.USDUpdateRequest.SerializeToString,
            usd__sync__pb2.USDUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchUSDUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/USDSync/WatchUSDUpdates',
            usd__sync__pb2.WatchRequest.SerializeToString,
            usd__sync__pb2.USDUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
